INSERT Items(ID,Titel,Categorie,Postcode,Locatie,Land,Verkoper,Prijs,Valuta,Conditie,Thumbnail,Beschrijving) VALUES (121485029250,'Opruiming!! Partijtje van diverse sieraden NIEUW!!',97120,'6446SK','Nederland','NL','maybrittsverige','1.99','EUR','Nieuw zonder labels','img121485029250.jpg','<div><br></div><div><font size="2">Partijtje bestaat uit:</font></div><div><font size="2"><br></font></div><div><font size="2">3 armbandjes</font></div><div><font size="2">1 ring maat 17</font></div><div><font size="2">8 paar oorbellen</font></div><div><font size="2"><br></font></div><div><font size="2" color="#ff0010"><b>Om verzendkosten te besparen kunt u objecten maximaal 3 weken verzamelen.</b></font></div><div><font size="2" color="#ff0010"><b><br></b></font></div><div><font size="2" color="#ff0010"><b>Tot 10 kilo = € 6,95 verzendkosten</b></font></div>')
INSERT Illustraties (ItemID,IllustratieFile) VALUES (121485029250,'dt_1_121485029250.jpg')
INSERT Items(ID,Titel,Categorie,Postcode,Locatie,Land,Verkoper,Prijs,Valuta,Conditie,Thumbnail,Beschrijving) VALUES (121485029261,'Partijtje van 6 dames jeans jasjes diverze maten ',97120,'6446SK','Nederland','NL','maybrittsverige','9.99','EUR','Nieuw met labels','img121485029261.jpg','<font face="Arial" size="2">3 x maat 38 in een van de jasjes maat 38 staat maat 48 maar dat klopt niet</font><div><font face="Arial" size="2"><br></font></div><div><font face="Arial" size="2">1 x maat &nbsp;42</font></div><div><font face="Arial" size="2"><br></font></div><div><font face="Arial" size="2">2 x maat 44</font></div><div><font face="Arial" size="2"><br></font></div><div><font face="Arial" size="2" color="#ff0010"><b>Om verzendkosten te besparen kunt u objecten maximaal 3 weken verzamelen.</b></font></div><div><font face="Arial" size="2" color="#ff0010"><b><br></b></font></div><div><font face="Arial" size="2" color="#ff0010"><b>Tot 10 kilo = € 6,95</b></font></div><div><font face="Arial" size="2" color="#ff0010"><b><br></b></font></div><div><font face="Arial" size="2" color="#ff0010"><b><br></b></font></div><div><font color="#ff0010"><b>Via DHL kan ik dit object verzenden voor € 4,00 mits u het zelf ophaalt bij een DHL Servicepoint bij u in de buurt.</b></font></div>')
INSERT Illustraties (ItemID,IllustratieFile) VALUES (121485029261,'dt_1_121485029261.jpg')
INSERT Items(ID,Titel,Categorie,Postcode,Locatie,Land,Verkoper,Prijs,Valuta,Conditie,Thumbnail,Beschrijving) VALUES (121485029267,'Opruiming!! Partijtje van diverse sieraden NIEUW!!',97120,'6446SK','Nederland','NL','maybrittsverige','1.99','EUR','Nieuw zonder labels','img121485029267.jpg','<div><br></div><div><font size="2">Partijtje bestaat uit:</font></div><div><font size="2"><br></font></div><div><font size="2">3 armbandjes</font></div><div><font size="2">1 ring maat 17</font></div><div><font size="2">10 paar oorbellen</font></div><div><font size="2"><br></font></div><div><font size="2" color="#ff0010"><b>Om verzendkosten te besparen kunt u objecten maximaal 3 weken verzamelen.</b></font></div><div><font size="2" color="#ff0010"><b><br></b></font></div><div><font size="2" color="#ff0010"><b>Tot 10 kilo = € 6,95 verzendkosten</b></font></div>')
INSERT Illustraties (ItemID,IllustratieFile) VALUES (121485029267,'dt_1_121485029267.jpg')
INSERT Items(ID,Titel,Categorie,Postcode,Locatie,Land,Verkoper,Prijs,Valuta,Conditie,Thumbnail,Beschrijving) VALUES (201216753146,'Clothes for men and women, 0,40 cent per kilogram!',97120,'2982CR','Nederland','NL','kringloop-ridderkerk','0.5','EUR','Tweedehands','img201216753146.jpg','<!--eBayMobile-Description-Text-->We are selling clothes per kilogram for 0,50 cents!<br>Clothes include men, women and kid clothes.<br><br>Make a nice bid and the clothes are yours for the taking!<br><br>P.S. Clothes in the pic are only a small amount of the batch of the various clothes we have!<!--eBayMobile-End--><br><!--eBayMobile-Signature-Text--><!--eBayMobile-End-->')
INSERT Illustraties (ItemID,IllustratieFile) VALUES (201216753146,'dt_1_201216753146.jpg')
INSERT Items(ID,Titel,Categorie,Postcode,Locatie,Land,Verkoper,Prijs,Valuta,Conditie,Thumbnail,Beschrijving) VALUES (290016132345,'ZWARTE TRUI VAN HET MERK S.C.B. (SCABETTI)',97120,'1078','Amsterdam,Nederland','NL','active1venter','10.0','EUR','','img290016132345.jpg','<P><STRONG><FONT face=verdana size=3>NIEUW ZWARTE TRUI MET KORTE MOUW VAN HET MERK S.C.B. OFTEWEL SCABETTI/ITALY MET V-HALS</FONT></STRONG></P>
<P><STRONG><FONT face=Verdana size=3>MATERIAAL IS 50% VISCOSE 50% ACRYL</FONT></STRONG></P>
<P><STRONG><FONT face=Verdana size=3>DE STOF VALT OM JE HEEN IS NIET STRAKZITTEND. DOOR DE COMBINATIE VAN TWEE BREISTEEKSOORTEN GEEFT DIT EEN MOOI EN</FONT></STRONG></P>
<P><STRONG><FONT face=Verdana size=3>APART EFFECT (ZIE FOTO) TRUI IN PLASTIC VERPAKT MET LABEL</FONT></STRONG></P>
<P><STRONG><FONT face=Verdana size=3>KORTE MOUW ZEKER IN DEZE PERIODE NIET TE WARM EN NIET TE KOUD JE KAN HET CASUAL OF NETJES OP EEN BROEK DRAGEN EN</FONT></STRONG></P>
<P><STRONG><FONT face=Verdana size=3>ZWART MIXT ZICH MET ELKE KLEUR </FONT></STRONG></P>
<P><STRONG><FONT face=Verdana size=3>TRUI LOOPT RECHT EN KOMT HALVERWEGE JE KONT</FONT></STRONG></P>
<P><STRONG><FONT face=Verdana size=3>DE MATEN 1&nbsp;x M, 2&nbsp;x L, 2x XL, 1&nbsp;x XXL alleen in deze maten en alleen de</FONT></STRONG></P>
<P><STRONG><FONT face=Verdana size=3>hier aangegeven aantallen</FONT></STRONG></P>')
INSERT Illustraties (ItemID,IllustratieFile) VALUES (290016132345,'dt_3_290016132345.jpg')
INSERT Illustraties (ItemID,IllustratieFile) VALUES (290016132345,'dt_1_290016132345.jpg')
INSERT Illustraties (ItemID,IllustratieFile) VALUES (290016132345,'dt_2_290016132345.jpg')
INSERT Items(ID,Titel,Categorie,Postcode,Locatie,Land,Verkoper,Prijs,Valuta,Conditie,Thumbnail,Beschrijving) VALUES (290016136200,' HERENTRUI VAN HET MERK S.C.B. (SCABETTI) KLEUR GRIJS',97120,'1078','Amsterdam,Nederland','NL','active1venter','10.0','EUR','','img290016136200.jpg','<P><STRONG><FONT face=verdana size=3>NIEUW&nbsp;MUISGRIJZE TRUI MET KORTE MOUW VAN HET MERK S.C.B. OFTEWEL SCABETTI/ITALY MET V-HALS</FONT></STRONG></P>
<P><STRONG><FONT face=Verdana size=3>MATERIAAL IS 50% VISCOSE 50% ACRYL</FONT></STRONG></P>
<P><STRONG><FONT face=Verdana size=3>DE STOF VALT OM JE HEEN IS NIET STRAKZITTEND.&nbsp;ER ZIT EEN KABELMOTIEF IN DE TRUI MET AAN DE HALSBOORD EN ONDERKANT EEN ZWART STREEP&nbsp;</FONT></STRONG><STRONG><FONT face=Verdana size=3> (ZIE FOTO) TRUI IN PLASTIC VERPAKT MET LABEL</FONT></STRONG></P>
<P><STRONG><FONT face=Verdana size=3>KORTE MOUW ZEKER IN DEZE PERIODE NIET TE WARM EN NIET TE KOUD JE KAN HET CASUAL OF NETJES OP EEN BROEK DRAGEN&nbsp;</FONT></STRONG></P>
<P><STRONG><FONT face=Verdana size=3>RONDOM BUIKGEDEELTE&nbsp;IS DE TRUI WAT RUIMER(!)&nbsp;</FONT></STRONG></P>
<P><STRONG><FONT face=Verdana size=3>TRUI&nbsp; KOMT TOT OP JE ACHTERWERK&nbsp;</FONT></STRONG></P>
<P><STRONG><FONT face=Verdana size=3>DE MATEN 1&nbsp;x M, 2&nbsp;x L, 2x XL, 1&nbsp;x XXL alleen in deze maten en alleen de</FONT></STRONG></P>
<P><STRONG><FONT face=Verdana size=3>hier aangegeven aantallen</FONT></STRONG></P>')
INSERT Illustraties (ItemID,IllustratieFile) VALUES (290016136200,'dt_3_290016136200.jpg')
INSERT Illustraties (ItemID,IllustratieFile) VALUES (290016136200,'dt_2_290016136200.jpg')
INSERT Illustraties (ItemID,IllustratieFile) VALUES (290016136200,'dt_1_290016136200.jpg')
INSERT Illustraties (ItemID,IllustratieFile) VALUES (290016136200,'dt_4_290016136200.jpg')
