INSERT Items(ID,Titel,Categorie,Postcode,Locatie,Land,Verkoper,Prijs,Valuta,Conditie,Thumbnail,Beschrijving) VALUES (131354729368,'Turbo SIM Unlock special voor de i-phone 4',77355,'1060','Amsterdam,Nederland','NL','royo-products','12.99','EUR','Nieuw','img131354729368.jpg','<font color="blue"><span style="FONT-FAMILY: Arial; FONT-SIZE: 10pt"><font color="#000000"><font face="Verdana"><font size="3"><font size="3"><font color="blue"><span style="FONT-FAMILY: Arial; FONT-SIZE: 10pt"></span>
<div align="center">
<div>NU VERKRIJBAAR NIEUWSTE VERSIE&nbsp; ! Nieuwste versie tot iOS 4.3 iPhone 4 met iOS 4.1 (Baseband 02.10.04) </div>
<div>iPhone 4 met iOS 4.2.1 (Baseband 03.10.01) <br>iPhone 4 met iOS 4.3 (Baseband 04.10.01) <br>iPhone 4 met iOS 4.3.1 (Baseband 04.10.01) </div>
<div><br>NIEUW ----&gt; iPhone 4 met iOS 4.3.2 (Baseband 04.10.01) &lt;---- NIEUW <br><br><font color="#ff0000"><u>Turbo SIM Unlock special voor de Iphone 4NIEUWSTE VERSIE <br><br></u></font>Geen extra Software nodig! Met deze Unlock SIM hoef je je Iphone niet te jailbreaken dus je garantie bij Apple blijft bestaan! Geschikt voor alle netwerken ondersteund ook 3G netwerken en internet en mail <br>Betrouwbaar &amp; makkelijk te instaleren. Funktioneerd voor 100%. <br><br>bij levering Inbegrepen: <br>Unlock SIM in gesealde verpakking <br>Handleiding en link naar instuctie&nbsp; video.</div><br></div>
<div align="center"><strong><font color="#00008b">*****************</font></strong></div>
<div align="center"><font color="#ff0000"><strong><u>&nbsp;</u></strong></font></div>
</font></font></font></font></font></span></font><div align="center"><font color="blue"><font color="#000000"><font face="Verdana"><font size="3"><font size="3"><font color="blue"></font></font></font></font></font></font><font color="#0000ff"><font face="Verdana">Bekijk mijn </font></font><a href="http://search.ebay.nl/_W0QQsassZroyo-productsQQhtZ-1" target="_blank"><font color="#0000ff" face="Verdana">andere objecten</font></a><font color="#0000ff"><font face="Verdana">!</font><a href="http://stores.ebay.nl/royoproducts"><font face="Verdana"><img class="imageAlign" alt="" src="http://pics.ebaystatic.com/aw/pics/nl/icon/imgWinkels_71x16.gif" border="0"></font></a></font></div>
<p style="MARGIN: 0cm 0cm 0pt; mso-pagination: none; mso-layout-grid-align: none" class="MsoNormal"><font face="Verdana"></font>&nbsp;</p>

<p><font face="Verdana">&nbsp;</font><a href="http://my.ebay.nl/ws/eBayISAPI.dll?AcceptSavedSeller&amp;linkname=includenewsletter&amp;sellerid=royo-products"><font color="#0000ff" face="Verdana">Schrijf je in voor mijn nieuwsbrieven</font></a><font color="#0000ff" face="Verdana"> door mijn eBay-winkel aan je favorieten toe te voegen.</font></p>
<center><img src="http://pics.ebay.com/aw/pics/sell/templates/images/k2/tagline.gif" border="0"> <br><font size="2" face="Arial,Helvetica">Gemaakt door <a href="http://pages.ebay.nl/turbo_lister/">eBay Turbo Lister</a>. <br>De gratis aanbiedingstool. Bied je objecten snel en gemakkelijk aan en beheer je actieve objecten. </font></center><br><font rwr="1" style="font-family:Arial" size="2"><p><font size="4" color="#992211"><strong>voor verzending naar het buitenland zijn de genoemde verzendkosten voor normale verzending, <u>zonder</u> track &amp; trace (<u>eigen risico</u>)</strong></font></p> <p><font size="4" color="#992211"><strong>voor verzending <u>met</u> track &amp; trace is uw <u>zending verzekerd</u>.</strong></font></p> <p><strong><font size="4" color="#992211">deze kosten zijn nog niet verwerkt in de genoemde verzendkosten.</font></strong></p></font>')
INSERT Illustraties (ItemID,IllustratieFile) VALUES (131354729368,'dt_1_131354729368.jpg')
INSERT Items(ID,Titel,Categorie,Postcode,Locatie,Land,Verkoper,Prijs,Valuta,Conditie,Thumbnail,Beschrijving) VALUES (161457706136,'Turbo SIM Unlock special voor de i-phone 4',77355,'1060','Amsterdam,Nederland','NL','royo-products','12.99','EUR','Nieuw','img161457706136.jpg','<font color="blue"><span style="FONT-FAMILY: Arial; FONT-SIZE: 10pt"><font color="#000000"><font face="Verdana"><font size="3"><font size="3"><font color="blue"><span style="FONT-FAMILY: Arial; FONT-SIZE: 10pt"></span>
<div align="center">
<div>NU VERKRIJBAAR NIEUWSTE VERSIE&nbsp; ! Nieuwste versie tot iOS 4.3 iPhone 4 met iOS 4.1 (Baseband 02.10.04) </div>
<div>iPhone 4 met iOS 4.2.1 (Baseband 03.10.01) <br>iPhone 4 met iOS 4.3 (Baseband 04.10.01) <br>iPhone 4 met iOS 4.3.1 (Baseband 04.10.01) </div>
<div><br>NIEUW ----&gt; iPhone 4 met iOS 4.3.2 (Baseband 04.10.01) &lt;---- NIEUW <br><br><font color="#ff0000"><u>Turbo SIM Unlock special voor de Iphone 4NIEUWSTE VERSIE <br><br></u></font>Geen extra Software nodig! Met deze Unlock SIM hoef je je Iphone niet te jailbreaken dus je garantie bij Apple blijft bestaan! Geschikt voor alle netwerken ondersteund ook 3G netwerken en internet en mail <br>Betrouwbaar &amp; makkelijk te instaleren. Funktioneerd voor 100%. <br><br>bij levering Inbegrepen: <br>Unlock SIM in gesealde verpakking <br>Handleiding en link naar instuctie&nbsp; video.</div><br></div>
<div align="center"><strong><font color="#00008b">*****************</font></strong></div>
<div align="center"><font color="#ff0000"><strong><u>&nbsp;</u></strong></font></div>
</font></font></font></font></font></span></font><div align="center"><font color="blue"><font color="#000000"><font face="Verdana"><font size="3"><font size="3"><font color="blue"></font></font></font></font></font></font><font color="#0000ff"><font face="Verdana">Bekijk mijn </font></font><a href="http://search.ebay.nl/_W0QQsassZroyo-productsQQhtZ-1" target="_blank"><font color="#0000ff" face="Verdana">andere objecten</font></a><font color="#0000ff"><font face="Verdana">!</font><a href="http://stores.ebay.nl/royoproducts"><font face="Verdana"><img class="imageAlign" alt="" src="http://pics.ebaystatic.com/aw/pics/nl/icon/imgWinkels_71x16.gif" border="0"></font></a></font></div>
<p style="MARGIN: 0cm 0cm 0pt; mso-pagination: none; mso-layout-grid-align: none" class="MsoNormal"><font face="Verdana"></font>&nbsp;</p>

<p><font face="Verdana">&nbsp;</font><a href="http://my.ebay.nl/ws/eBayISAPI.dll?AcceptSavedSeller&amp;linkname=includenewsletter&amp;sellerid=royo-products"><font color="#0000ff" face="Verdana">Schrijf je in voor mijn nieuwsbrieven</font></a><font color="#0000ff" face="Verdana"> door mijn eBay-winkel aan je favorieten toe te voegen.</font></p>
<center><img src="http://pics.ebay.com/aw/pics/sell/templates/images/k2/tagline.gif" border="0"> <br><font size="2" face="Arial,Helvetica">Gemaakt door <a href="http://pages.ebay.nl/turbo_lister/">eBay Turbo Lister</a>. <br>De gratis aanbiedingstool. Bied je objecten snel en gemakkelijk aan en beheer je actieve objecten. </font></center><br><font rwr="1" style="font-family:Arial" size="2"><p><font size="4" color="#992211"><strong>voor verzending naar het buitenland zijn de genoemde verzendkosten voor normale verzending, <u>zonder</u> track &amp; trace (<u>eigen risico</u>)</strong></font></p> <p><font size="4" color="#992211"><strong>voor verzending <u>met</u> track &amp; trace is uw <u>zending verzekerd</u>.</strong></font></p> <p><strong><font size="4" color="#992211">deze kosten zijn nog niet verwerkt in de genoemde verzendkosten.</font></strong></p></font>')
INSERT Illustraties (ItemID,IllustratieFile) VALUES (161457706136,'dt_1_161457706136.jpg')
INSERT Items(ID,Titel,Categorie,Postcode,Locatie,Land,Verkoper,Prijs,Valuta,Conditie,Thumbnail,Beschrijving) VALUES (221607177397,'PTT Nummerdiskette Versie 1.0 1995 originele verpakking',77355,'ST72HX','Verenigd Koninkrijk','GB','hans6075','0.35','EUR','Tweedehands','img221607177397.jpg','Handleiding is bijgeleverd.<br>
<br>
Deze nummerdiskette werd uitgegeven in 1995 om de telefoonnummers van toen naar het 10-nummerige systeem om te zetten.<br><br>Zie foto<br>
<br>Zie ook mijn andere advertenties.<br><br>
')
INSERT Illustraties (ItemID,IllustratieFile) VALUES (221607177397,'dt_1_221607177397.jpg')
INSERT Items(ID,Titel,Categorie,Postcode,Locatie,Land,Verkoper,Prijs,Valuta,Conditie,Thumbnail,Beschrijving) VALUES (231395238268,'windows xp // VERSIE 2002, originele cd met code',77355,'3081SV','Nederland','NL','joop61','9.5','EUR','Tweedehands','img231395238268.jpg','<p style="margin-bottom: 0cm"><font color="#000000"><font face="Times New Roman, serif"><font size="4">werkend,
geen garantie, geen retour<br>afhalen
aan de deur, verzenden 4 euro 50<br>opbrengst
gaat naar www.dierenthuis.nl<br>kijk
ook naar mijn andere advertenties..</font></font></font></p>')
INSERT Illustraties (ItemID,IllustratieFile) VALUES (231395238268,'dt_1_231395238268.jpg')
